[package]
name = "pwm_multi_project"
version = "0.1.0"
authors = ["Denis Puthier <denis.puthier@univ-amu.fr>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
regex = "1.3.1"
scoped_threadpool = "0.1.9"